// Action users
export const REQUEST_USERS_LOGIN = 'REQUEST_USERS_LOGIN'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const REQUEST_LOADING = 'REQUEST_LOADING'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REQUEST_CURRENT_TOKEN = 'REQUEST_CURRENT_TOKEN'
// Action Posts
export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS'
export const REQUEST_ADD_POSTS = 'REQUEST_ADD_POSTS'
export const REQUEST_DELETE_POSTS = 'REQUEST_DELETE_POSTS'
export const REQUEST_UPDATE_POSTS = 'REQUEST_UPDATE_POSTS'
export const REQUEST_FILTER_POSTS = 'REQUEST_FILTER_POSTS'
